# Generated by Django 4.1.2 on 2022-10-18 14:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(help_text="User's account balance", verbose_name='balance')),
                ('user', models.ForeignKey(help_text="User's account", on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Item's name", max_length=128, verbose_name='Item')),
                ('description', models.CharField(max_length=512)),
                ('price', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0.01, 'Price can not be less than 0.01')])),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(help_text='Money amount change', verbose_name='Amount')),
                ('account', models.ForeignKey(help_text='Transaction', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.account', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': ('Transaction',),
                'verbose_name_plural': ('Transactions',),
                'ordering': ('-id',),
            },
        ),
    ]
