# Generated by Django 4.1.2 on 2022-10-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-id',), 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, help_text="User's account balance", max_digits=10, verbose_name='balance'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(help_text='Item description', max_length=512, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='price of item', max_digits=10, verbose_name='price'),
        ),
    ]
