# Generated by Django 4.1.2 on 2022-10-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_options_alter_account_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Money amount change', max_digits=10, verbose_name='Amount'),
        ),
    ]
