# Generated by Django 4.1.2 on 2022-10-21 18:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, help_text="User's account balance", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'), 'Account balance can not be negative.')], verbose_name='balance'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(check=models.Q(('balance__gte', Decimal('0'))), name='Balance below zero is not allowed.'),
        ),
    ]
