# Generated by Django 4.1.2 on 2022-10-23 16:25

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_account_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="User's account balance", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'), 'Account balance can not be negative.')], verbose_name='balance'),
        ),
    ]
